### ISSUE TITLE
python-pytorch-rocm 1.12.1-5 seems to be broken

### ISSUE THREAD

**Issue by jellersby** [arch4edu/arch4edu#203] opened 2022-12-13 06:41 UTC
I was able to install this package successfully: python-pytorch-rocm 1.12.1-5

Trying to use it fails though:
```
$ python
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/rocm/lib/librocsolver.so.0: undefined symbol: _Z31rocblas_internal_syr2k_templateILb0ELb1EPKfS1_PfE15rocblas_status_P15_rocblas_handle13rocblas_fill_18rocblas_operation_iiT1_T2_lilS9_lilS8_T3_lili
```

I'm going to try to build it from the PKGBUILD using makepkg.

**Comment by cybaol** [comment] 2022-12-16 04:51
`opencv3-opt` is also outdate and needs rebuild.

**Comment by jellersby** [comment] 2022-12-20 06:34
Just a quick update to say that `import torch` now works! However, it's still not fully functional:

```
$ python
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; reference = const char*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: IOT instruction (core dumped)  python
```

Thank you.

**Comment by dentette** [comment] 2022-12-20 16:13
I have the same issue, it seems to be because the packages were build with the _GLIBCXX_ASSERTIONS flag enabled.

**Comment by wuxxin** [comment] 2022-12-24 03:39
i tried pytorch 1.13.1 using the pullrequest https://github.com/rocm-arch/python-pytorch-rocm/pull/62 and updated sources (1.13.0 -> 1.13.1) which compiled, but trying to use it throws the same error.

```
ipython
from torch.utils.cpp_extension import ROCM_HOME 
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp,
_Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) 
[with _Tp = const char*; _Alloc = std::allocator<const char*>; 
reference = const char*&; size_type = long unsigned int]: Assertion 
'__n < this->size()' failed.
```

**Comment by petronny** [comment] 2022-12-24 09:18
Basic rocm packages are being moved to [community]. We have to wait longer to trigger the rebuild.

**Comment by jellersby** [comment] 2022-12-25 05:54
> Basic rocm packages are being moved to [community]. We have to wait longer to trigger the rebuild.

Exciting! Thanks for letting us know. Is there any place we can track the progress of the move?

**Comment by petronny** [comment] 2022-12-26 07:03
> Is there any place we can track the progress of the move?

They are already in  [community-testing] now. But I can't tell when they will be moved to [community]

**Comment by wuxxin** [comment] 2022-12-27 14:09
the error currently thrown, looks similar to https://github.com/rocm-arch/rocm-arch/issues/928 

The error does not give information where it happend, a `gdb`backtrace shows 
```
#0  0x00007f50b2cfd64c n/a (libc.so.6 + 
#1  0x00007f50b2cad958 raise (libc.so.6 + 0x38958)
#2  0x00007f50b2c9753d abort (libc.so.6 + 0x2253d)
#3  0x00007f50ab065112 _ZSt21__glibcxx_assert_failPKciS0_S0_ (libstdc++.so.6 + 0xd2112)
#4  0x00007f5057347a95 n/a (libhsa-runtime64.so.1 + 0x71a95)
#5  0x00007f5057347f28 n/a (libhsa-runtime64.so.1 + 0x71f28)
#6  0x00007f50573480bc n/a (libhsa-runtime64.so.1 + 0x720bc)
#7  0x00007f505732717f n/a (libhsa-runtime64.so.1 + 0x5117f)
#8  0x00007f509104eb6b n/a (libamdhip64.so.5 + 0x2b0b6b)
#9  0x00007f5090e48108 n/a (libamdhip64.so.5 + 0xaa108)
#10 0x00007f5090e68fad hipGetDeviceCount (libamdhip64.so.5 + 0xcafad)
#11 0x00007f50923c65c5 _ZN3c103hip28device_count_ensure_non_zeroEv (libc10_hip.so + 0x3c5c5)
#12 0x00007f5094517f9a n/a (libtorch_hip.so + 0x213cf9a)
#13 0x00007f50aa96ba0c n/a (libtorch_python.so + 0xb66a0c)
```

because it shows libhsa-runtime64 as last caller before the assertation, but my hip-runtime-amd is the newest available, which already has a fix to build without assertations, so its probably somewhere else in the calling chain.

Anybody an idea how to find the calling library thats responsible for the assertation ?

**Comment by wuxxin** [comment] 2022-12-27 14:17
the calling argument for the above backtrace was done using:
```sh
HIP_LAUNCH_BLOCKING=1 AMD_LOG_LEVEL=3 \
  python -c "import torch;d=torch.device('cuda:0') a=torch.randn(100,device=d,dtype=torch.float);print(a)"
```

**Comment by petronny** [comment] 2022-12-29 04:46
> `opencv3-opt` is also outdate and needs rebuild.

[aff3c0a](https://github.com/arch4edu/arch4edu/commit/aff3c0a75085f354b5eec460e9b002eea0f9de6b)

**Comment by jellersby** [comment] 2023-01-14 06:52
I just tried a fresh install of `python-pytorch-rocm` to see if the situation had improved.

I couldn't check if the assertion error had been fixed, because the `torch` module failed load at all, citing a missing library (`libopencv_highgui`).

```
$ python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: libopencv_highgui.so.406: cannot open shared object file: No such file or directory
```

**Comment by dentette** [comment] 2023-01-14 08:01
> I just tried a fresh install of `python-pytorch-rocm` to see if the situation had improved.
> 
> I couldn't check if the assertion error had been fixed, because the `torch` module failed load at all, citing a missing library (`libopencv_highgui`).
> 
> ```
> $ python
> Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
>     from torch._C import *  # noqa: F403
> ImportError: libopencv_highgui.so.406: cannot open shared object file: No such file or directory
> ```

This is because opencv is on version 4.0.7, downgrading to 4.0.6 resolves this issue and it goes back to the assertion problem

**Comment by jellersby** [comment] 2023-01-17 05:41
I went to build `python-pytorch-rocm` myself, which succeeded.

Then I went to build python-torchvision-rocm, and this is what happened during the build:

```
Successfully preprocessed all matching files.
Total number of unsupported CUDA function calls: 0
Total number of replaced kernel launches: 15
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; reference = const char*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/home/jellersby/Development/aur/python-torchvision-rocm/PKGBUILD: line 58: 435886 Aborted                 (core dumped) FORCE_CUDA=1 TORCHVISION_USE_NVJPEG=0 TORCHVISION_USE_VIDEO_CODEC=0 CC=gcc CXX=g++ python setup.py build
```

And I'm not even using any arch4edu packages. I'm using packages from community-testing, and then building the remaining ones myself.

**Comment by petronny** [comment] 2023-01-20 09:23
Well, I'll try to build `python-pytorch-rocm` against [testing]. https://github.com/arch4edu/arch4edu/commit/3bcb3aaf6ffdc5d9e602930e1ce1f7391afc9018

But please remind me to revert it when the rocm packages go to [community].

**Comment by petronny** [comment] 2023-01-20 10:53
Oops, building the rest rocm packages against those in [testing] raises lots of core dump errors.

https://github.com/arch4edu/cactus/actions/runs/3966811619
https://github.com/arch4edu/cactus/actions/runs/3966770212

Seems that the rocm packages in [testing] are not ready yet.

**Comment by jellersby** [comment] 2023-01-21 02:31
> Oops, building the rest rocm packages against those in [testing] raises lots of core dump errors.
> 
> https://github.com/arch4edu/cactus/actions/runs/3966811619 https://github.com/arch4edu/cactus/actions/runs/3966770212
> 
> Seems that the rocm packages in [testing] are not ready yet.

This will likely be of interest to @tpkessler, if it helps suss out some issues with the rocm packages in testing.

**Comment by petronny** [comment] 2023-01-21 05:06
I've rebuilt python-pytorch-rocm against the rocm packages in arch4edu.

https://github.com/arch4edu/arch4edu/commit/cd49f24c69d093cd9aef8f8d8470957ae0d00e1a

**Comment by jellersby** [comment] 2023-01-21 05:51
Thanks @petronny, I just installed all of the latest packages from arch4edu. The debug assertions issue is still present, interestingly enough. cc @tpkessler

```
>>> torch.cuda.is_available()
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; reference = const char*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

**Comment by tpkessler** [comment] 2023-01-25 12:12
The build errors with rocrand and rocsparse are fixed with the latest package updates. They were caused by LTO.

**Comment by petronny** [comment] 2023-02-15 09:33
`python-pytorch-rocm` is now in [community].

**Closed by petronny** 2023-02-15 09:33 UTC
Labels: rebuild
